### ISSUE TITLE
No support for URL Prefix / cname

### ISSUE THREAD

**Issue by johnwbaxter** [a-digital/assetindexer#2] opened 2016-12-15 10:55 UTC
Hi,

I'm trying this plugin but from what i can see, it's not pulling in the URL Prefix / cname and is forcing a region into the url?

I have modified it to stop that happening, but whilst the import now runs, i get the following readout and no assets get added. Any guidance would be appreciated!
![screen shot 2016-12-15 at 10 51 06](https://cloud.githubusercontent.com/assets/338729/21221338/e68a6948-c2b4-11e6-80f3-ea11eb49df92.png)

**Comment by matt-adigital** [comment] 2016-12-15 11:19
Hi John,

Thanks for trying our plugin out. When you see the Count 1157 of 0 message, is this after the previous steps have shown up like so: Count 1156 of 1157, or do they all show as Count x of 0?

Also can you navigate to /cms/assetindexer/file/{{ sourceHandle }} to kick off the file indexing manually?

The modification you have made may potentially need to be added to the getFiles function within the AssetIndexerService also.

Please let me know how you get on with this after trying the above.

**Comment by johnwbaxter** [comment] 2016-12-15 11:31
Hey Matt,

They all show as Count x of 0.

If i navigate to that url, i get "Count: 1 of 0"

I had modified the getFiles method with my adjustment already.

For testing purposes, i have manually specified the endpoint in the options array:

```
$options = [
'version'     => 'latest',
'region'      => 'us-east-1',
'credentials' => $credentials,
'endpoint' => 'http://s3.amazonaws.com/my-bucket-hkjdhfg76f7d8',
'bucket_endpoint' => true
];
```

Thanks!

**Comment by matt-adigital** [comment] 2016-12-15 11:44
If they are all showing as count x of 0 then the $totalfiles variable mustn't be populating itself correctly. What happens if you were to add in the following directly underneath the `$num_files = count($totalfiles);` command?
```
echo "<pre>";
print_r($totalfiles);
exit;
```
As the total count is returning as zero I would expect you to see some error to be displayed to do with the scandir() function. Either this could be a php version error to do with the environment, or it could be that the directories url stored in the $dir variable could not be reached so the value for $dir must be updated.

**Comment by johnwbaxter** [comment] 2016-12-15 11:58
Is this to be put in getFiles or getAssets?

**Comment by matt-adigital** [comment] 2016-12-15 12:12
This depends upon which url you are testing on, if you are clicking through then place it in getAssets. However, if you have navigated to the url I mentioned in my previous comment then put it in getFiles. If you aren't sure and want to be covered either way then it won't hurt at all to stick it in both of them.

**Comment by johnwbaxter** [comment] 2016-12-15 12:14
Ok, i get '0' from that!

Thanks!

**Comment by matt-adigital** [comment] 2016-12-15 12:16
What do you get if you change this to `print_r(scandir($dir))`, I suggest this as we are performing an array_diff on this to remove the thumbs folders and a few extras.

**Comment by johnwbaxter** [comment] 2016-12-15 12:18
Looks like it returns an empty array:

```
Array
(
)
```

**Comment by matt-adigital** [comment] 2016-12-15 12:21
This couldn't be caused by the assets on S3 not being set to public could it? As by sounds of it there are no php errors telling you that scandir() has failed. Could you just go into S3 and right click any file, and then hit the "Make Public" button and try it again? Just making sure here as sometimes we can overthink things in situations like this.

**Comment by johnwbaxter** [comment] 2016-12-15 12:22
Hmm, that is a really good question actually! I can't get access to it for an hour or two, but i will check that as soon as i get access.

Thanks Matt!

**Comment by matt-adigital** [comment] 2016-12-15 12:24
You're welcome John. Sometimes for all our php knowledge it can be the "simple" bits that trip us up in the end haha. Let me know how you get on when you've got access. Good luck, I'm hoping that this is the issue here and we can get it sorted for you.

**Comment by johnwbaxter** [comment] 2016-12-15 13:41
Files set to public, but still having the same issue here i'm afraid.

**Comment by matt-adigital** [comment] 2016-12-15 13:49
In your craft config file, is devMode set to true? Enabling this should allow us to see any php errors which are occurring.

**Comment by johnwbaxter** [comment] 2016-12-15 13:52
Yes, debug = true but no errors from this in the logs!

**Comment by matt-adigital** [comment] 2016-12-15 13:54
How about devMode? It would allow us to see php errors in the browser rather than having to go to the logs. https://craftcms.com/support/dev-mode

**Comment by johnwbaxter** [comment] 2016-12-15 13:54
Sorry, i meant devmode previously, not debug!

**Comment by matt-adigital** [comment] 2016-12-15 14:01
And there are still no php warnings or notices displayed when you print_r() followed by exit? Interesting, can you upload a file through the assets section of the CMS to just check that the S3 settings have connected up with the bucket correctly?

This plugin uses the settings held within the asset source so I am wondering if there is an issue here causing the connection to not find any files.

**Comment by johnwbaxter** [comment] 2016-12-15 14:04
Nope, no warnings or notices.

I'm running a routine on the data to see if i can do this a different way, when that is done i will test the S3 settings. I'm 99% sure s3 is setup fine though!

Thanks!

**Comment by matt-adigital** [comment] 2016-12-15 14:11
The other thing I can think of which might be causing this after looking through the code is if you haven't set a subfolder for the bucket. If this is the case then please change
```
$dir = "s3://".$settings->bucket."/".$settings->subfolder."/";
```
to
```
$dir = "s3://".$settings->bucket."/";
if (isset($settings->subfolder) && $settings->subfolder <> "") {
	$dir .= $settings->subfolder."/";
}
```
And this should sort it out hopefully if you have no subfolder set on the asset source. After finding this I will add the conditional to the core files of the plugin once we have sorted out your issues.

**Comment by johnwbaxter** [comment] 2016-12-15 14:38
Ok, i will take a look at that also, thanks!

**Comment by matt-adigital** [comment] 2016-12-16 14:13
Hi John,

Did you have any luck after changing the plugin to include that conditional around the subfolder settings?

**Comment by matt-adigital** [comment] 2017-01-23 11:02
Hi John, I've put out a new release with the conditional above added. I've also added cpTrigger support. I hope you got to the bottom of your issues in the end. I'm going to close this issue for now but feel free to get in touch if you need anything else.

**Closed as completed by matt-adigital** 2017-01-23 11:02 UTC
